### ISSUE TITLE
How to output error code instead of missing partial?

### ISSUE THREAD

**Issue by w0rm** [raycmorgan/Mu#48]
Hi, I'm trying to listen on output stream for error message and then emit it as data, but it doesn't work — the request hangs up and never returns. I need to output error message instead of missing partial, and keep all the rest blocks rendered.

Is there a way to solve my problem?

```
pageData = ""
pageStream = mu.compileAndRender fileName

pageStream.on "data", (data) ->
  pageData += data

pageStream.on "end", ->
  stream = mu.compileAndRender "layout.html", {page: pageData}
  util.pump stream, response

pageStream.on "error", (err) ->
  pageStream.emit 'data', err.message
  # pageStream.emit 'end'
```

**Comment by atk** [comment]
You could try to overwrite mu.fs
