### ISSUE TITLE
partials with mu-cli.js

### ISSUE THREAD

**Issue by gibatronic** [raycmorgan/Mu#68]
hey guys, I was playing with `mu-cli.js` and couldn't make partials work...

`partial.html`
```html
<h1>yo-ho-ho</h1>
```

`template.html`
```html
<html>
  <body>
    {{> partial}}
  </body>
</html>
```

command:
```sh
cat template.html | node_modules/mu2/lib/mu-cli.js --view={}
```

output:
```html
<html>
  <body>
    
  </body>
</html>
```

desired output:
```html
<html>
  <body>
    <h1>yo-ho-ho</h1>
  </body>
</html>
```

am I doing something wrong?

**Comment by gibatronic** [comment]
it seems that there's nothing wrong, `mu-cli.js` just wasn't meant to handle partials... so I took some time to change it in that pull request. please accept it if you found it useful.

**Comment by EvandroLG** [comment]
+1

**Comment by evandroeisinger** [comment]
+1

**Comment by gibatronic** [comment]
well... forget it, I'll just use [janl/mustache.js](https://github.com/janl/mustache.js).
