### ISSUE TITLE
.write( string, encoding, offset, length is deprecated notice

### ISSUE THREAD

**Issue by kangaskahn** [raycmorgan/Mu#70]
Here's a fix for the error:
/node_modules/mu2/mu/parser.js
Line 67 should be replaced with:

`      buffer.write(content, 0, 'utf8');`

**Comment by mykiimike** [comment]
Same
Trace: .write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
    at Buffer.write (buffer.js:400:17)
    at Object.Parser.scanText (/mu2/lib/mu/parser.js:67:14)
    at Object.Parser.tokenize (/mu2/lib/mu/parser.js:32:38)
    at Object.exports.parse (/mu2/lib/mu/parser.js:11:17)
    at /mu2/lib/mu.js:40:21
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by smebberson** [comment]
I got this too. The fix can be:

```
buffer.write(content);
```

In this case, other values are appropriately defaulted.

**Comment by theUtherSide** [comment]
`buffer.write(content, 0, content.length, 'utf8');` worked for me.

**Comment by tiagojsalmeida** [comment]
+1

**Comment by raycmorgan** [comment]
Merged https://github.com/raycmorgan/Mu/pull/71 to fix.
